#!/bin/sh

set -e

case "$1" in
    upgrade) ;;
    remove|failed-upgrade|deconfigure)
        update-alternatives --remove moc "/usr/bin/moc-qt4"
        update-alternatives --remove uic "/usr/bin/uic-qt4"
        update-alternatives --remove qmake "/usr/bin/qmake-qt4"
        update-alternatives --remove lupdate "/usr/bin/lupdate-qt4"
        update-alternatives --remove lrelease "/usr/bin/lrelease-qt4"
        ;;
esac

#DEBHELPER#
