usr/lib/libQtCore.so.*
usr/lib/libQtCLucene.so.*
usr/lib/qt4/plugins/codecs/*.so
usr/share/qt4/translations/qt_ar.qm
usr/share/qt4/translations/qt_ca.qm
usr/share/qt4/translations/qt_de.qm
usr/share/qt4/translations/qt_es.qm
usr/share/qt4/translations/qt_fr.qm
usr/share/qt4/translations/qt_iw.qm
usr/share/qt4/translations/qt_ja_jp.qm
usr/share/qt4/translations/qt_pl.qm
usr/share/qt4/translations/qt_pt.qm
usr/share/qt4/translations/qt_ru.qm
usr/share/qt4/translations/qt_sk.qm
usr/share/qt4/translations/qt_sv.qm
usr/share/qt4/translations/qt_uk.qm
usr/share/qt4/translations/qt_zh_CN.qm
usr/share/qt4/translations/qt_zh_TW.qm


