#!/bin/sh

set -e

update-alternatives --install \
    /usr/bin/moc moc "/usr/bin/moc-qt4" "40" \
    --slave /usr/share/man/man1/moc.1.gz moc.1.gz \
    "/usr/share/man/man1/moc-qt4.1.gz"

update-alternatives --install \
    /usr/bin/uic uic "/usr/bin/uic-qt4" "40" \
    --slave /usr/share/man/man1/uic.1.gz uic.1.gz \
    "/usr/share/man/man1/uic-qt4.1.gz"

update-alternatives --install \
    /usr/bin/qmake qmake "/usr/bin/qmake-qt4" "40" \
    --slave /usr/share/man/man1/qmake.1.gz qmake.1.gz \
    "/usr/share/man/man1/qmake-qt4.1.gz"

update-alternatives --install \
    /usr/bin/lupdate lupdate "/usr/bin/lupdate-qt4" "40" \
    --slave /usr/share/man/man1/lupdate.1.gz lupdate.1.gz \
    "/usr/share/man/man1/lupdate-qt4.1.gz"

update-alternatives --install \
    /usr/bin/lrelease lrelease "/usr/bin/lrelease-qt4" "40" \
    --slave /usr/share/man/man1/lrelease.1.gz lrelease.1.gz \
    "/usr/share/man/man1/lrelease-qt4.1.gz"

#DEBHELPER#
